name: Deploy Streamlit App to Streamlit Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Streamlit deployment step (manual for GitHub Pages/Streamlit Sharing)
      run: echo "✅ Push to main - ready for Streamlit deployment"